# Generated by Django 5.0.6 on 2024-05-15 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="PopDataTable",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "Age_Group",
                    models.CharField(max_length=200, verbose_name="Age_Group"),
                ),
                ("Male_Estimate", models.BigIntegerField(verbose_name="Male_Estimate")),
                (
                    "Percent_Male_Estimate",
                    models.FloatField(verbose_name="Percent_Male_Estimate"),
                ),
                (
                    "Female_Estimate",
                    models.BigIntegerField(verbose_name="Female_Estimate"),
                ),
                (
                    "Percent_Female_Estimate",
                    models.FloatField(verbose_name="Percent_Female_Estimate"),
                ),
            ],
        ),
    ]
